[DM-25428] Upgrade jdk to 8 for travis build
Looks like we had an error building with jdk7 due to it being too
old.  So let's try jdk8 instead.

This is what the error looked like:

java.lang.UnsupportedClassVersionError: ca/nrc/cadc/util/Log4jInit : Unsupported major.minor version 52.0